### ISSUE TITLE
Extract io.reactivex.rxjava2 into a separate artifact

### ISSUE THREAD

**Issue by johnjohndoe** [ShabanKamell/android-form-validator#2]
I noticed that your library has a transitive dependency to _RxJava2_. This is a rather large artifact which not every project likes to include. Therefore, I suggest to move this part of the code into a separate module.
Here is a [library project of mine with separate modules](https://github.com/johnjohndoe/c3media-base) for you to get inspired.
Thanks for considering.

**Comment by MalekKamel** [comment]
Thanks johnjohndoe , it's done in version 2.0.0.
