### ISSUE TITLE
Can we use Validation logic out side library 

### ISSUE THREAD

**Issue by MahmoudMabrok** [ShabanKamell/android-form-validator#4]
Is it possible to have **a sub-module** of validation logic to be used in apps without `formView`

**Comment by MalekKamel** [comment]
Hi Mahmoud,

If I understand you well, you can use FormEditText anywhere in your layout without Form layout. In this case you can invoke `FormEditText.validate()` and this function will return a boolean indicating the validation result.

Thanks
